url: https://beacon.clcert.cl
baseurl: 

# Site settings
title: CLCERT Random Beacon
email: beacon@clcert.cl
description: "Site for the CLCERT Random Beacon service, providing autonomous, unpredictable, consistent and verifiable randomness."


# Team names, titles and social links
people:
- name: Alejandro Hevia
  pic: alejandro
  position: Principal Investigator
  social:
    - title: envelope
      url: mailto:ahevia@dcc.uchile.cl
    - title: twitter
      url: https://www.twitter.com/ahevia

- name: Camilo Gómez
  pic: camilo
  position: Main Engineer and Developer
  social:
    - title: envelope
      url: mailto:cgomez@clcert.cl
    - title: twitter
      url: https://www.twitter.com/milogomez__

- name: Cristián Rojas
  pic: cristian
  position: Software Security Engineer
  social:
    - title: envelope
      url: mailto:crirojas@clcert.cl
    - title: twitter
      url: https://www.twitter.com/InjenieroBarsa

- name: Sergio Miranda
  pic: sergio
  position: Network Engineer
  social:
    - title: envelope
      url: #
    - title: twitter
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/clcert
  - title: github
    url: http://github.com/clcert

# Build settings
markdown: kramdown
permalink: pretty